version: '3.3'

volumes:
  prometheus: {}

networks:
  mon_net:
    external:
      name: mon_net

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - mon_net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command: 
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"

  web:
    image: my-web-app:latest
    ports:
      - "80:80"
    networks:
      - mon_net

  nginx-exporter:
    image: "nginx/nginx-prometheus-exporter:latest"
    ports:
      - "9113:9113"
    networks:
      - mon_net
    command: ["-nginx.scrape-uri=http://web/metrics"]
